logging:
    level:
        org.springframework.web: INFO
        cn.itdebug.wx.api: DEBUG

# Tomcat
#server:
#    tomcat:
#        uri-encoding: UTF-8
#        connection-timeout: 5000
#        threads:
#            max: 1000
#            min-spare: 30
#    port: ${SERVER_PORT:8088}
#    servlet:
#        context-path: /wx


spring:
    # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
            enabled: true
    mvc:
        throw-exception-if-no-handler-found: true
        pathmatch:
            matching-strategy: ant_path_matcher #解决springboot2.6与swagger兼容性问题
    task:
        scheduling:
            pool:
                size: 5

springfox:
    documentation:
        swagger-ui:
            enabled: true